from __future__ import annotations

from dataclasses import dataclass
from typing import Final

MUTATING_METHODS: Final[tuple[str, ...]] = ('POST', 'PUT', 'PATCH', 'DELETE')

@dataclass(frozen=True, slots=True)
class OperationDef:
    operation_id: str
    command_name: str
    method: str
    path: str
    summary: str
    tag: str
    path_params: tuple[str, ...]
    query_params: tuple[str, ...]
    body_params: tuple[str, ...]
    has_body: bool
    multipart: bool
    response_kind: str

OPERATIONS: Final[tuple[OperationDef, ...]] = (
    OperationDef(
        operation_id='docs_display',
        command_name='docs_display',
        method='GET',
        path='/docs',
        summary='Load the docs page for the API.',
        tag='docs',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='text',
    ),
    OperationDef(
        operation_id='docs_json',
        command_name='docs_json',
        method='GET',
        path='/docs.json',
        summary='Show a JSON view of the API docs data.',
        tag='docs',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='pages_list',
        command_name='pages_list',
        method='GET',
        path='/pages',
        summary='Get a listing of pages visible to the user.',
        tag='pages',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='pages_create',
        command_name='pages_create',
        method='POST',
        path='/pages',
        summary='Create a new page in the system.',
        tag='pages',
        path_params=(),
        query_params=(),
        body_params=('book_id', 'chapter_id', 'name', 'html', 'markdown', 'tags', 'priority'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='pages_read',
        command_name='pages_read',
        method='GET',
        path='/pages/{id}',
        summary='View the details of a single page. Pages will always have HTML content. They may have markdown content if the Markdown editor was used to last update the page.',
        tag='pages',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='pages_update',
        command_name='pages_update',
        method='PUT',
        path='/pages/{id}',
        summary='Update the details of a single page.',
        tag='pages',
        path_params=('id',),
        query_params=(),
        body_params=('book_id', 'chapter_id', 'name', 'html', 'markdown', 'tags', 'priority'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='pages_delete',
        command_name='pages_delete',
        method='DELETE',
        path='/pages/{id}',
        summary='Delete a page. This will typically send the page to the recycle bin.',
        tag='pages',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='pages_exportHtml',
        command_name='pages_export_html',
        method='GET',
        path='/pages/{id}/export/html',
        summary='Export a page as a contained HTML file.',
        tag='pages',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='pages_exportPdf',
        command_name='pages_export_pdf',
        method='GET',
        path='/pages/{id}/export/pdf',
        summary='Export a page as a PDF file.',
        tag='pages',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='pages_exportPlainText',
        command_name='pages_export_plain_text',
        method='GET',
        path='/pages/{id}/export/plaintext',
        summary='Export a page as a plain text file.',
        tag='pages',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='pages_exportMarkdown',
        command_name='pages_export_markdown',
        method='GET',
        path='/pages/{id}/export/markdown',
        summary='Export a page as a markdown file.',
        tag='pages',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='pages_exportZip',
        command_name='pages_export_zip',
        method='GET',
        path='/pages/{id}/export/zip',
        summary='Export a page as a contained ZIP file.',
        tag='pages',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='chapters_list',
        command_name='chapters_list',
        method='GET',
        path='/chapters',
        summary='Get a listing of chapters visible to the user.',
        tag='chapters',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='chapters_create',
        command_name='chapters_create',
        method='POST',
        path='/chapters',
        summary='Create a new chapter in the system.',
        tag='chapters',
        path_params=(),
        query_params=(),
        body_params=('book_id', 'name', 'description', 'description_html', 'tags', 'priority', 'default_template_id'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='chapters_read',
        command_name='chapters_read',
        method='GET',
        path='/chapters/{id}',
        summary='View the details of a single chapter.',
        tag='chapters',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='chapters_update',
        command_name='chapters_update',
        method='PUT',
        path='/chapters/{id}',
        summary="Update the details of a single chapter. Providing a 'book_id' property will essentially move the chapter into that parent element if you have permissions to do so.",
        tag='chapters',
        path_params=('id',),
        query_params=(),
        body_params=('book_id', 'name', 'description', 'description_html', 'tags', 'priority', 'default_template_id'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='chapters_delete',
        command_name='chapters_delete',
        method='DELETE',
        path='/chapters/{id}',
        summary='Delete a chapter. This will typically send the chapter to the recycle bin.',
        tag='chapters',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='chapters_exportHtml',
        command_name='chapters_export_html',
        method='GET',
        path='/chapters/{id}/export/html',
        summary='Export a chapter as a contained HTML file.',
        tag='chapters',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='chapters_exportPdf',
        command_name='chapters_export_pdf',
        method='GET',
        path='/chapters/{id}/export/pdf',
        summary='Export a chapter as a PDF file.',
        tag='chapters',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='chapters_exportPlainText',
        command_name='chapters_export_plain_text',
        method='GET',
        path='/chapters/{id}/export/plaintext',
        summary='Export a chapter as a plain text file.',
        tag='chapters',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='chapters_exportMarkdown',
        command_name='chapters_export_markdown',
        method='GET',
        path='/chapters/{id}/export/markdown',
        summary='Export a chapter as a markdown file.',
        tag='chapters',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='chapters_exportZip',
        command_name='chapters_export_zip',
        method='GET',
        path='/chapters/{id}/export/zip',
        summary='Export a chapter as a contained ZIP file.',
        tag='chapters',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='books_list',
        command_name='books_list',
        method='GET',
        path='/books',
        summary='Get a listing of books visible to the user.',
        tag='books',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='books_create',
        command_name='books_create',
        method='POST',
        path='/books',
        summary="Create a new book in the system. The cover image of a book can be set by sending a file via an 'image' property within a 'multipart/form-data' request. If the 'image' property is null then the book cover image will be removed.",
        tag='books',
        path_params=(),
        query_params=(),
        body_params=('name', 'description', 'description_html', 'tags', 'image', 'default_template_id'),
        has_body=True,
        multipart=True,
        response_kind='json',
    ),
    OperationDef(
        operation_id='books_read',
        command_name='books_read',
        method='GET',
        path='/books/{id}',
        summary="View the details of a single book. The response data will contain a 'content' property listing the chapter and pages directly within, in the same structure as you'd see within the BookStack interface when viewing a book. Top-level contents will have a 'type' property to distinguish between pages and chapters.",
        tag='books',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='books_update',
        command_name='books_update',
        method='PUT',
        path='/books/{id}',
        summary="Update the details of a single book. The cover image of a book can be set by sending a file via an 'image' property within a 'multipart/form-data' request. If the 'image' property is null then the book cover image will be removed.",
        tag='books',
        path_params=('id',),
        query_params=(),
        body_params=('name', 'description', 'description_html', 'tags', 'image', 'default_template_id'),
        has_body=True,
        multipart=True,
        response_kind='json',
    ),
    OperationDef(
        operation_id='books_delete',
        command_name='books_delete',
        method='DELETE',
        path='/books/{id}',
        summary='Delete a single book. This will typically send the book to the recycle bin.',
        tag='books',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='books_exportHtml',
        command_name='books_export_html',
        method='GET',
        path='/books/{id}/export/html',
        summary='Export a book as a contained HTML file.',
        tag='books',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='books_exportPdf',
        command_name='books_export_pdf',
        method='GET',
        path='/books/{id}/export/pdf',
        summary='Export a book as a PDF file.',
        tag='books',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='books_exportPlainText',
        command_name='books_export_plain_text',
        method='GET',
        path='/books/{id}/export/plaintext',
        summary='Export a book as a plain text file.',
        tag='books',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='books_exportMarkdown',
        command_name='books_export_markdown',
        method='GET',
        path='/books/{id}/export/markdown',
        summary='Export a book as a markdown file.',
        tag='books',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='books_exportZip',
        command_name='books_export_zip',
        method='GET',
        path='/books/{id}/export/zip',
        summary='Export a book as a contained ZIP export file.',
        tag='books',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='shelves_list',
        command_name='shelves_list',
        method='GET',
        path='/shelves',
        summary='Get a listing of shelves visible to the user.',
        tag='shelves',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='shelves_create',
        command_name='shelves_create',
        method='POST',
        path='/shelves',
        summary="Create a new shelf in the system. An array of books IDs can be provided in the request. These will be added to the shelf in the same order as provided. The cover image of a shelf can be set by sending a file via an 'image' property within a 'multipart/form-data' request. If the 'image' property is null then the shelf cover image will be removed.",
        tag='shelves',
        path_params=(),
        query_params=(),
        body_params=('name', 'description', 'description_html', 'books', 'tags', 'image'),
        has_body=True,
        multipart=True,
        response_kind='json',
    ),
    OperationDef(
        operation_id='shelves_read',
        command_name='shelves_read',
        method='GET',
        path='/shelves/{id}',
        summary='View the details of a single shelf.',
        tag='shelves',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='shelves_update',
        command_name='shelves_update',
        method='PUT',
        path='/shelves/{id}',
        summary="Update the details of a single shelf. An array of books IDs can be provided in the request. These will be added to the shelf in the same order as provided and overwrite any existing book assignments. The cover image of a shelf can be set by sending a file via an 'image' property within a 'multipart/form-data' request. If the 'image' property is null then the shelf cover image will be removed.",
        tag='shelves',
        path_params=('id',),
        query_params=(),
        body_params=('name', 'description', 'description_html', 'books', 'tags', 'image'),
        has_body=True,
        multipart=True,
        response_kind='json',
    ),
    OperationDef(
        operation_id='shelves_delete',
        command_name='shelves_delete',
        method='DELETE',
        path='/shelves/{id}',
        summary='Delete a single shelf. This will typically send the shelf to the recycle bin.',
        tag='shelves',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='attachments_list',
        command_name='attachments_list',
        method='GET',
        path='/attachments',
        summary='Get a listing of attachments visible to the user. The external property indicates whether the attachment is simple a link. A false value for the external property would indicate a file upload.',
        tag='attachments',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='attachments_create',
        command_name='attachments_create',
        method='POST',
        path='/attachments',
        summary='Create a new attachment in the system. An uploaded_to value must be provided containing an ID of the page that this upload will be related to.',
        tag='attachments',
        path_params=(),
        query_params=(),
        body_params=('name', 'uploaded_to', 'file', 'link'),
        has_body=True,
        multipart=True,
        response_kind='json',
    ),
    OperationDef(
        operation_id='attachments_read',
        command_name='attachments_read',
        method='GET',
        path='/attachments/{id}',
        summary="Get the details & content of a single attachment of the given ID. The attachment link or file content is provided via a 'content' property. For files the content will be base64 encoded.",
        tag='attachments',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='attachments_update',
        command_name='attachments_update',
        method='PUT',
        path='/attachments/{id}',
        summary='Update the details of a single attachment. As per the create endpoint, if a file is being provided as the attachment content the request should be formatted as a multipart/form-data request instead of JSON.',
        tag='attachments',
        path_params=('id',),
        query_params=(),
        body_params=('name', 'uploaded_to', 'file', 'link'),
        has_body=True,
        multipart=True,
        response_kind='json',
    ),
    OperationDef(
        operation_id='attachments_delete',
        command_name='attachments_delete',
        method='DELETE',
        path='/attachments/{id}',
        summary='Delete an attachment of the given ID.',
        tag='attachments',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='audit_log_list',
        command_name='audit_log_list',
        method='GET',
        path='/audit-log',
        summary='Get a listing of audit log events in the system. The loggable relation fields currently only relates to core content types (page, book, bookshelf, chapter) but this may be used more in the future across other types. Requires permission to manage both users and system settings.',
        tag='audit-log',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='comments_list',
        command_name='comments_list',
        method='GET',
        path='/comments',
        summary='Get a listing of comments visible to the user.',
        tag='comments',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='comments_create',
        command_name='comments_create',
        method='POST',
        path='/comments',
        summary="Create a new comment on a page. If commenting as a reply to an existing comment, the 'reply_to' parameter should be provided, set to the 'local_id' of the comment being replied to.",
        tag='comments',
        path_params=(),
        query_params=(),
        body_params=('page_id', 'reply_to', 'html', 'content_ref'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='comments_read',
        command_name='comments_read',
        method='GET',
        path='/comments/{id}',
        summary='Read the details of a single comment, along with its direct replies.',
        tag='comments',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='comments_update',
        command_name='comments_update',
        method='PUT',
        path='/comments/{id}',
        summary='Update the content or archived status of an existing comment.',
        tag='comments',
        path_params=('id',),
        query_params=(),
        body_params=('html', 'archived'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='comments_delete',
        command_name='comments_delete',
        method='DELETE',
        path='/comments/{id}',
        summary='Delete a single comment from the system.',
        tag='comments',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='content_permissions_read',
        command_name='content_permissions_read',
        method='GET',
        path='/content-permissions/{contentType}/{contentId}',
        summary='Read the configured content-level permissions for the item of the given type and ID.',
        tag='content-permissions',
        path_params=('contentType', 'contentId'),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='content_permissions_update',
        command_name='content_permissions_update',
        method='PUT',
        path='/content-permissions/{contentType}/{contentId}',
        summary="Update the configured content-level permission overrides for the item of the given type and ID. 'contentType' should be one of: page, book, chapter, bookshelf.",
        tag='content-permissions',
        path_params=('contentType', 'contentId'),
        query_params=(),
        body_params=('owner_id', 'role_permissions', 'role_permissions.*.role_id', 'role_permissions.*.view', 'role_permissions.*.create', 'role_permissions.*.update', 'role_permissions.*.delete', 'fallback_permissions', 'fallback_permissions.inheriting', 'fallback_permissions.view', 'fallback_permissions.create', 'fallback_permissions.update', 'fallback_permissions.delete'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='image_gallery_list',
        command_name='image_gallery_list',
        method='GET',
        path='/image-gallery',
        summary="Get a listing of images in the system. Includes gallery (page content) images and drawings. Requires visibility of the page they're originally uploaded to.",
        tag='image-gallery',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='image_gallery_create',
        command_name='image_gallery_create',
        method='POST',
        path='/image-gallery',
        summary='Create a new image in the system.',
        tag='image-gallery',
        path_params=(),
        query_params=(),
        body_params=('type', 'uploaded_to', 'image', 'name'),
        has_body=True,
        multipart=True,
        response_kind='json',
    ),
    OperationDef(
        operation_id='image_gallery_readDataForUrl',
        command_name='image_gallery_read_data_for_url',
        method='GET',
        path='/image-gallery/url/data',
        summary='Read the image file data for a single image in the system, using the provided URL to identify the image instead of its ID, which is provided as a "URL" query parameter. The returned response will be a stream of image data instead of a JSON response.',
        tag='image-gallery',
        path_params=(),
        query_params=('url',),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='image_gallery_read',
        command_name='image_gallery_read',
        method='GET',
        path='/image-gallery/{id}',
        summary='View the details of a single image. The "thumbs" response property contains links to scaled variants that BookStack may use in its UI. The "content" response property provides HTML and Markdown content, in the format that BookStack would typically use by default to add the image in page content, as a convenience. Actual image file data is not provided but can be fetched via the "url" response property or by using the "read-data" endpoint.',
        tag='image-gallery',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='image_gallery_readData',
        command_name='image_gallery_read_data',
        method='GET',
        path='/image-gallery/{id}/data',
        summary='Read the image file data for a single image in the system. The returned response will be a stream of image data instead of a JSON response.',
        tag='image-gallery',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='binary',
    ),
    OperationDef(
        operation_id='image_gallery_update',
        command_name='image_gallery_update',
        method='PUT',
        path='/image-gallery/{id}',
        summary='Update the details of an existing image in the system. Since "image" is expected to be a file, this needs to be a \'multipart/form-data\' type request if providing a new image file. Updated image files should be of the same file type as the original image.',
        tag='image-gallery',
        path_params=('id',),
        query_params=(),
        body_params=('name', 'image'),
        has_body=True,
        multipart=True,
        response_kind='json',
    ),
    OperationDef(
        operation_id='image_gallery_delete',
        command_name='image_gallery_delete',
        method='DELETE',
        path='/image-gallery/{id}',
        summary='Delete an image from the system. Will also delete thumbnails for the image. Does not check or handle image usage so this could leave pages with broken image references.',
        tag='image-gallery',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='imports_list',
        command_name='imports_list',
        method='GET',
        path='/imports',
        summary='List existing ZIP imports visible to the user. Requires permission to import content.',
        tag='imports',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='imports_create',
        command_name='imports_create',
        method='POST',
        path='/imports',
        summary='Start a new import from a ZIP file. This does not actually run the import since that is performed via the "run" endpoint. This uploads, validates and stores the ZIP file so it\'s ready to be imported.',
        tag='imports',
        path_params=(),
        query_params=(),
        body_params=('file',),
        has_body=True,
        multipart=True,
        response_kind='json',
    ),
    OperationDef(
        operation_id='imports_read',
        command_name='imports_read',
        method='GET',
        path='/imports/{id}',
        summary='Read details of a pending ZIP import. The "details" property contains high-level metadata regarding the ZIP import content, and the structure of this will change depending on import "type". Requires permission to import content.',
        tag='imports',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='imports_run',
        command_name='imports_run',
        method='POST',
        path='/imports/{id}',
        summary='Run the import process for an uploaded ZIP import. The "parent_id" and "parent_type" parameters are required when the import type is "chapter" or "page". On success, this endpoint returns the imported item. Requires permission to import content.',
        tag='imports',
        path_params=('id',),
        query_params=(),
        body_params=('parent_type', 'parent_id'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='imports_delete',
        command_name='imports_delete',
        method='DELETE',
        path='/imports/{id}',
        summary='Delete a pending ZIP import from the system. Requires permission to import content.',
        tag='imports',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='recycle_bin_list',
        command_name='recycle_bin_list',
        method='GET',
        path='/recycle-bin',
        summary='Get a top-level listing of the items in the recycle bin. The "deletable" property will reflect the main item deleted. For books and chapters, counts of child pages/chapters will be loaded within this "deletable" data. For chapters & pages, the parent item will be loaded within this "deletable" data. Requires permission to manage both system settings and permissions.',
        tag='recycle-bin',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='recycle_bin_restore',
        command_name='recycle_bin_restore',
        method='PUT',
        path='/recycle-bin/{deletionId}',
        summary='Restore a single deletion from the recycle bin. Requires permission to manage both system settings and permissions.',
        tag='recycle-bin',
        path_params=('deletionId',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='recycle_bin_destroy',
        command_name='recycle_bin_destroy',
        method='DELETE',
        path='/recycle-bin/{deletionId}',
        summary='Remove a single deletion from the recycle bin. Use this endpoint carefully as it will entirely remove the underlying deleted items from the system. Requires permission to manage both system settings and permissions.',
        tag='recycle-bin',
        path_params=('deletionId',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='roles_list',
        command_name='roles_list',
        method='GET',
        path='/roles',
        summary='Get a listing of roles in the system. Requires permission to manage roles.',
        tag='roles',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='roles_create',
        command_name='roles_create',
        method='POST',
        path='/roles',
        summary='Create a new role in the system. Permissions should be provided as an array of permission name strings. Requires permission to manage roles.',
        tag='roles',
        path_params=(),
        query_params=(),
        body_params=('display_name', 'description', 'mfa_enforced', 'external_auth_id', 'permissions', 'permissions.*'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='roles_read',
        command_name='roles_read',
        method='GET',
        path='/roles/{id}',
        summary='View the details of a single role. Provides the permissions and a high-level list of the users assigned. Requires permission to manage roles.',
        tag='roles',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='roles_update',
        command_name='roles_update',
        method='PUT',
        path='/roles/{id}',
        summary='Update an existing role in the system. Permissions should be provided as an array of permission name strings. An empty "permissions" array would clear granted permissions. In many cases, where permissions are changed, you\'ll want to fetch the existing permissions and then modify before providing in your update request. Requires permission to manage roles.',
        tag='roles',
        path_params=('id',),
        query_params=(),
        body_params=('display_name', 'description', 'mfa_enforced', 'external_auth_id', 'permissions', 'permissions.*'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='roles_delete',
        command_name='roles_delete',
        method='DELETE',
        path='/roles/{id}',
        summary='Delete a role from the system. Requires permission to manage roles.',
        tag='roles',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='search_all',
        command_name='search_all',
        method='GET',
        path='/search',
        summary="Run a search query against all main content types (shelves, books, chapters & pages) in the system. Takes the same input as the main search bar within the BookStack interface as a 'query' parameter. See https://www.bookstackapp.com/docs/user/searching/ for a full list of search term options. Results contain a 'type' property to distinguish between: bookshelf, book, chapter & page.",
        tag='search',
        path_params=(),
        query_params=('query', 'page', 'count'),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='system_read',
        command_name='system_read',
        method='GET',
        path='/system',
        summary='Read details regarding the BookStack instance. Some details may be null where not set, like the app logo for example.',
        tag='system',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='users_list',
        command_name='users_list',
        method='GET',
        path='/users',
        summary='Get a listing of users in the system. Requires permission to manage users.',
        tag='users',
        path_params=(),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='users_create',
        command_name='users_create',
        method='POST',
        path='/users',
        summary='Create a new user in the system. Requires permission to manage users.',
        tag='users',
        path_params=(),
        query_params=(),
        body_params=('name', 'email', 'external_auth_id', 'language', 'password', 'roles', 'roles.*', 'send_invite'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='users_read',
        command_name='users_read',
        method='GET',
        path='/users/{id}',
        summary='View the details of a single user. Requires permission to manage users.',
        tag='users',
        path_params=('id',),
        query_params=(),
        body_params=(),
        has_body=False,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='users_update',
        command_name='users_update',
        method='PUT',
        path='/users/{id}',
        summary='Update an existing user in the system. Requires permission to manage users.',
        tag='users',
        path_params=('id',),
        query_params=(),
        body_params=('name', 'email', 'external_auth_id', 'language', 'password', 'roles', 'roles.*'),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
    OperationDef(
        operation_id='users_delete',
        command_name='users_delete',
        method='DELETE',
        path='/users/{id}',
        summary='Delete a user from the system. Can optionally accept a user id via `migrate_ownership_id` to indicate who should be the new owner of their related content. Requires permission to manage users.',
        tag='users',
        path_params=('id',),
        query_params=(),
        body_params=('migrate_ownership_id',),
        has_body=True,
        multipart=False,
        response_kind='json',
    ),
)

OPERATIONS_BY_COMMAND: Final[dict[str, OperationDef]] = {op.command_name: op for op in OPERATIONS}
