from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True, slots=True)
class OperationDef:
    operation_id: str
    command_name: str
    method: str
    path: str
    summary: str
    tag: str
    path_params: tuple[str, ...]
    query_params: tuple[str, ...]
    has_body: bool


OPERATIONS: Final[tuple[OperationDef, ...]] = (
    OperationDef(
        operation_id='activateWorkflow',
        command_name='activate_workflow',
        method='POST',
        path='/workflows/{id}/activate',
        summary='Publish a workflow',
        tag='Workflow',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='addUsersToProject',
        command_name='add_users_to_project',
        method='POST',
        path='/projects/{projectId}/users',
        summary='Add one or more users to a project',
        tag='Projects',
        path_params=('projectId',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='archiveWorkflow',
        command_name='archive_workflow',
        method='POST',
        path='/workflows/{id}/archive',
        summary='Archive a workflow',
        tag='Workflow',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='changeRole',
        command_name='change_role',
        method='PATCH',
        path='/users/{id}/role',
        summary="Change a user's global role",
        tag='User',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='changeUserRoleInProject',
        command_name='change_user_role_in_project',
        method='PATCH',
        path='/projects/{projectId}/users/{userId}',
        summary="Change a user's role in a project",
        tag='Projects',
        path_params=('projectId', 'userId'),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='createCredential',
        command_name='create_credential',
        method='POST',
        path='/credentials',
        summary='Create a credential',
        tag='Credential',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='createDataTable',
        command_name='create_data_table',
        method='POST',
        path='/data-tables',
        summary='Create a new data table',
        tag='DataTable',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='createProject',
        command_name='create_project',
        method='POST',
        path='/projects',
        summary='Create a project',
        tag='Projects',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='createTag',
        command_name='create_tag',
        method='POST',
        path='/tags',
        summary='Create a tag',
        tag='Tags',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='createUser',
        command_name='create_user',
        method='POST',
        path='/users',
        summary='Create multiple users',
        tag='User',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='createVariable',
        command_name='create_variable',
        method='POST',
        path='/variables',
        summary='Create a variable',
        tag='Variables',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='createWorkflow',
        command_name='create_workflow',
        method='POST',
        path='/workflows',
        summary='Create a workflow',
        tag='Workflow',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='deactivateWorkflow',
        command_name='deactivate_workflow',
        method='POST',
        path='/workflows/{id}/deactivate',
        summary='Deactivate a workflow',
        tag='Workflow',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteCredential',
        command_name='delete_credential',
        method='DELETE',
        path='/credentials/{id}',
        summary='Delete credential by ID',
        tag='Credential',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteDataTable',
        command_name='delete_data_table',
        method='DELETE',
        path='/data-tables/{dataTableId}',
        summary='Delete a data table',
        tag='DataTable',
        path_params=('dataTableId',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteDataTableRows',
        command_name='delete_data_table_rows',
        method='DELETE',
        path='/data-tables/{dataTableId}/rows/delete',
        summary='Delete rows from a data table',
        tag='DataTable',
        path_params=('dataTableId',),
        query_params=('filter', 'returnData', 'dryRun'),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteExecution',
        command_name='delete_execution',
        method='DELETE',
        path='/executions/{id}',
        summary='Delete an execution',
        tag='Execution',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteProject',
        command_name='delete_project',
        method='DELETE',
        path='/projects/{projectId}',
        summary='Delete a project',
        tag='Projects',
        path_params=('projectId',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteTag',
        command_name='delete_tag',
        method='DELETE',
        path='/tags/{id}',
        summary='Delete a tag',
        tag='Tags',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteUser',
        command_name='delete_user',
        method='DELETE',
        path='/users/{id}',
        summary='Delete a user',
        tag='User',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteUserFromProject',
        command_name='delete_user_from_project',
        method='DELETE',
        path='/projects/{projectId}/users/{userId}',
        summary='Delete a user from a project',
        tag='Projects',
        path_params=('projectId', 'userId'),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteVariable',
        command_name='delete_variable',
        method='DELETE',
        path='/variables/{id}',
        summary='Delete a variable',
        tag='Variables',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='deleteWorkflow',
        command_name='delete_workflow',
        method='DELETE',
        path='/workflows/{id}',
        summary='Delete a workflow',
        tag='Workflow',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='generateAudit',
        command_name='generate_audit',
        method='POST',
        path='/audit',
        summary='Generate an audit',
        tag='Audit',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='getCredentialType',
        command_name='get_credential_type',
        method='GET',
        path='/credentials/schema/{credentialTypeName}',
        summary='Show credential data schema',
        tag='Credential',
        path_params=('credentialTypeName',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='getCredentials',
        command_name='get_credentials',
        method='GET',
        path='/credentials',
        summary='List credentials',
        tag='Credential',
        path_params=(),
        query_params=('limit', 'cursor'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getDataTable',
        command_name='get_data_table',
        method='GET',
        path='/data-tables/{dataTableId}',
        summary='Get a data table',
        tag='DataTable',
        path_params=('dataTableId',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='getDataTableRows',
        command_name='get_data_table_rows',
        method='GET',
        path='/data-tables/{dataTableId}/rows',
        summary='Retrieve rows from a data table',
        tag='DataTable',
        path_params=('dataTableId',),
        query_params=('limit', 'cursor', 'filter', 'sortBy', 'search'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getDiscover',
        command_name='get_discover',
        method='GET',
        path='/discover',
        summary='Discover available API capabilities',
        tag='Discover',
        path_params=(),
        query_params=('include', 'resource', 'operation'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getExecution',
        command_name='get_execution',
        method='GET',
        path='/executions/{id}',
        summary='Retrieve an execution',
        tag='Execution',
        path_params=('id',),
        query_params=('includeData', 'redactExecutionData'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getExecutionTags',
        command_name='get_execution_tags',
        method='GET',
        path='/executions/{id}/tags',
        summary='Get execution tags',
        tag='Execution',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='getExecutions',
        command_name='get_executions',
        method='GET',
        path='/executions',
        summary='Retrieve all executions',
        tag='Execution',
        path_params=(),
        query_params=('includeData', 'redactExecutionData', 'status', 'workflowId', 'projectId', 'limit', 'cursor'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getInstalledPackages',
        command_name='get_installed_packages',
        method='GET',
        path='/community-packages',
        summary='List installed community packages',
        tag='CommunityPackage',
        path_params=(),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='getProjectUsers',
        command_name='get_project_users',
        method='GET',
        path='/projects/{projectId}/users',
        summary='List project members',
        tag='Projects',
        path_params=('projectId',),
        query_params=('limit', 'cursor'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getProjects',
        command_name='get_projects',
        method='GET',
        path='/projects',
        summary='Retrieve projects',
        tag='Projects',
        path_params=(),
        query_params=('limit', 'cursor'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getTag',
        command_name='get_tag',
        method='GET',
        path='/tags/{id}',
        summary='Retrieves a tag',
        tag='Tags',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='getTags',
        command_name='get_tags',
        method='GET',
        path='/tags',
        summary='Retrieve all tags',
        tag='Tags',
        path_params=(),
        query_params=('limit', 'cursor'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getUser',
        command_name='get_user',
        method='GET',
        path='/users/{id}',
        summary='Get user by ID/Email',
        tag='User',
        path_params=('id',),
        query_params=('includeRole',),
        has_body=False,
    ),
    OperationDef(
        operation_id='getUsers',
        command_name='get_users',
        method='GET',
        path='/users',
        summary='Retrieve all users',
        tag='User',
        path_params=(),
        query_params=('limit', 'cursor', 'includeRole', 'projectId'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getVariables',
        command_name='get_variables',
        method='GET',
        path='/variables',
        summary='Retrieve variables',
        tag='Variables',
        path_params=(),
        query_params=('limit', 'cursor', 'projectId', 'state'),
        has_body=False,
    ),
    OperationDef(
        operation_id='getWorkflow',
        command_name='get_workflow',
        method='GET',
        path='/workflows/{id}',
        summary='Retrieve a workflow',
        tag='Workflow',
        path_params=('id',),
        query_params=('excludePinnedData',),
        has_body=False,
    ),
    OperationDef(
        operation_id='getWorkflowTags',
        command_name='get_workflow_tags',
        method='GET',
        path='/workflows/{id}/tags',
        summary='Get workflow tags',
        tag='Workflow',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='getWorkflowVersion',
        command_name='get_workflow_version',
        method='GET',
        path='/workflows/{id}/{versionId}',
        summary='Retrieves a specific version of a workflow',
        tag='Workflow',
        path_params=('id', 'versionId'),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='getWorkflows',
        command_name='get_workflows',
        method='GET',
        path='/workflows',
        summary='Retrieve all workflows',
        tag='Workflow',
        path_params=(),
        query_params=('active', 'tags', 'name', 'projectId', 'excludePinnedData', 'limit', 'cursor'),
        has_body=False,
    ),
    OperationDef(
        operation_id='insertDataTableRows',
        command_name='insert_data_table_rows',
        method='POST',
        path='/data-tables/{dataTableId}/rows',
        summary='Insert rows into a data table',
        tag='DataTable',
        path_params=('dataTableId',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='installPackage',
        command_name='install_package',
        method='POST',
        path='/community-packages',
        summary='Install a community package',
        tag='CommunityPackage',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='listDataTables',
        command_name='list_data_tables',
        method='GET',
        path='/data-tables',
        summary='List all data tables',
        tag='DataTable',
        path_params=(),
        query_params=('limit', 'cursor', 'filter', 'sortBy'),
        has_body=False,
    ),
    OperationDef(
        operation_id='pull',
        command_name='pull',
        method='POST',
        path='/source-control/pull',
        summary='Pull changes from the remote repository',
        tag='SourceControl',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='retryExecution',
        command_name='retry_execution',
        method='POST',
        path='/executions/{id}/retry',
        summary='Retry an execution',
        tag='Execution',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='stopExecution',
        command_name='stop_execution',
        method='POST',
        path='/executions/{id}/stop',
        summary='Stop an execution',
        tag='Execution',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='stopManyExecutions',
        command_name='stop_many_executions',
        method='POST',
        path='/executions/stop',
        summary='Stop multiple executions',
        tag='Execution',
        path_params=(),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='transferCredential',
        command_name='transfer_credential',
        method='PUT',
        path='/credentials/{id}/transfer',
        summary='Transfer a credential to another project.',
        tag='Credential',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='transferWorkflow',
        command_name='transfer_workflow',
        method='PUT',
        path='/workflows/{id}/transfer',
        summary='Transfer a workflow to another project',
        tag='Workflow',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='unarchiveWorkflow',
        command_name='unarchive_workflow',
        method='POST',
        path='/workflows/{id}/unarchive',
        summary='Unarchive a workflow',
        tag='Workflow',
        path_params=('id',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='uninstallPackage',
        command_name='uninstall_package',
        method='DELETE',
        path='/community-packages/{name}',
        summary='Uninstall a community package',
        tag='CommunityPackage',
        path_params=('name',),
        query_params=(),
        has_body=False,
    ),
    OperationDef(
        operation_id='updateCredential',
        command_name='update_credential',
        method='PATCH',
        path='/credentials/{id}',
        summary='Update credential by ID',
        tag='Credential',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='updateDataTable',
        command_name='update_data_table',
        method='PATCH',
        path='/data-tables/{dataTableId}',
        summary='Update a data table',
        tag='DataTable',
        path_params=('dataTableId',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='updateDataTableRows',
        command_name='update_data_table_rows',
        method='PATCH',
        path='/data-tables/{dataTableId}/rows/update',
        summary='Update rows in a data table',
        tag='DataTable',
        path_params=('dataTableId',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='updateExecutionTags',
        command_name='update_execution_tags',
        method='PUT',
        path='/executions/{id}/tags',
        summary='Update tags of an execution',
        tag='Execution',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='updatePackage',
        command_name='update_package',
        method='PATCH',
        path='/community-packages/{name}',
        summary='Update a community package',
        tag='CommunityPackage',
        path_params=('name',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='updateProject',
        command_name='update_project',
        method='PUT',
        path='/projects/{projectId}',
        summary='Update a project',
        tag='Projects',
        path_params=('projectId',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='updateTag',
        command_name='update_tag',
        method='PUT',
        path='/tags/{id}',
        summary='Update a tag',
        tag='Tags',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='updateVariable',
        command_name='update_variable',
        method='PUT',
        path='/variables/{id}',
        summary='Update a variable',
        tag='Variables',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='updateWorkflow',
        command_name='update_workflow',
        method='PUT',
        path='/workflows/{id}',
        summary='Update a workflow',
        tag='Workflow',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='updateWorkflowTags',
        command_name='update_workflow_tags',
        method='PUT',
        path='/workflows/{id}/tags',
        summary='Update tags of a workflow',
        tag='Workflow',
        path_params=('id',),
        query_params=(),
        has_body=True,
    ),
    OperationDef(
        operation_id='upsertDataTableRow',
        command_name='upsert_data_table_row',
        method='POST',
        path='/data-tables/{dataTableId}/rows/upsert',
        summary='Upsert a row in a data table',
        tag='DataTable',
        path_params=('dataTableId',),
        query_params=(),
        has_body=True,
    ),
)

OPERATIONS_BY_COMMAND: Final[dict[str, OperationDef]] = {op.command_name: op for op in OPERATIONS}
OPERATIONS_BY_ID: Final[dict[str, OperationDef]] = {op.operation_id: op for op in OPERATIONS}
MUTATING_METHODS: Final[frozenset[str]] = frozenset({"POST", "PUT", "PATCH", "DELETE"})
